# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            't'
tagline:          'A Jekyll theme'
description:      't'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Priyanka Dey'
  url:            https://priyanka-dey.github.io/

paginate:         5

# Custom vars
version:          2.1.0
show_date:        false 

github:
  repo:           https://github.com/poole/hyde
